### PR TITLE
Chunk api

### PR DESCRIPTION
**Pull request by sosthene-nitrokey**
This API adds a streaming API to write large files.

It stores chunks in volatile memory, and then commits them to static memory when writing is over.

### CODE REVIEW

**Comment by sosthene-nitrokey** [comment]
We might also want to consider an AEAD version of this API to be able to encrypt large files, likely using [aead::stream](https://docs.rs/aead/latest/aead/stream/index.html)

**Comment by sosthene-nitrokey** [comment]
I'm making this a draft. While implementing the chunked encrypted writes I'm realizing this API will need some modifications.

**Comment by robin-nitrokey** [comment]
Re. https://github.com/trussed-dev/trussed/pull/115 and this PR:  We talked about using extensions as a tool for experimenting with new requests before they are stabilized and merged into upstream Trussed.  Would that make sense here?

**Comment by sosthene-nitrokey** [comment]
I agree. I mentioned that in https://github.com/Nitrokey/trussed/pull/23

I think it would make sense to have these as extensions. The Chunk API could even use allocation in that case, and be much more straightforward for encrypted chunked writes (we could store everything in a `alloc::Vec<u8>` and encrypt/decrypt it with an AEAD in one go).

**Comment by sosthene-nitrokey** [comment]
Making it an extension would still require updates to the `filestore` trait and implementation.

**Comment by robin-nitrokey** [comment]
Isn’t it sufficient to access the `Store` directly?

**Comment by sosthene-nitrokey** [comment]
That's also an option

**Comment by robin-nitrokey** [comment]
I think we can close this for the time being and create a new PR if we want to upstream the extension.

**Pull request closed without merging**
