### PR TITLE
Remove firmware compilation tests

### PR DESCRIPTION
**Pull request by sosthene-nitrokey**
This will allow breaking change for an 0.2 release

### CODE REVIEW

**Comment by robin-nitrokey** [comment]
Can’t we just remove/comment the `on` triggers instead of commenting out all steps?

**Comment by sosthene-nitrokey** [comment]
There's actually an even better solution. We can manually disable it in the GH UI it seems: https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow. I think this is what we want. The two workflows were both named "CI" so I renamed it to "Firmwares". I uncommented the Nitrokey firmware too, so that we can just keep the file as-is and disable the workflow.

**Comment by sosthene-nitrokey** [comment]
Should we merge and disable now or wait for Friday's steering call?

**Comment by daringer** [comment]
let's wait for the steering call to align on a path how (and when) to migrate solo2 towards the breaking changes

**Pull request merged**
